### ISSUE TITLE
i got this eoror

### ISSUE THREAD

**Issue by KARONAGAMING** [adh319/Lunox#68]
### Bug description

i got this eoror then i play somethings

### Step to reproduce

when i use /play i got this eororo and didn't play anythings

### Operating system

Windows 10

### Nodejs version

20.9.0 and 18 all both tested but got the same eroor

### Errors / Logs

} reason: DiscordAPIError[50035]: Invalid Form Body
embeds[0].description[BASE_TYPE_REQUIRED]: This field is required
    at handleErrors (C:\Users\KARONAGAMING\Downloads\Compressed\Lunox-2.2.0\Lunox-2.2.0\node_modules\@discordjs\rest\dist\index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (C:\Users\KARONAGAMING\Downloads\Compressed\Lunox-2.2.0\Lunox-2.2.0\node_modules\@discordjs\rest\dist\index.js:1120:23)
    at async SequentialHandler.queueRequest (C:\Users\KARONAGAMING\Downloads\Compressed\Lunox-2.2.0\Lunox-2.2.0\node_modules\@discordjs\rest\dist\index.js:953:14)
    at async _REST.request (C:\Users\KARONAGAMING\Downloads\Compressed\Lunox-2.2.0\Lunox-2.2.0\node_modules\@discordjs\rest\dist\index.js:1266:22)
    at async InteractionWebhook.editMessage (C:\Users\KARONAGAMING\Downloads\Compressed\Lunox-2.2.0\Lunox-2.2.0\node_modules\discord.js\src\structures\Webhook.js:339:15)
    at async ChatInputCommandInteraction.editReply (C:\Users\KARONAGAMING\Downloads\Compressed\Lunox-2.2.0\Lunox-2.2.0\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:158:17)
    at async Object.run (C:\Users\KARONAGAMING\Downloads\Compressed\Lunox-2.2.0\Lunox-2.2.0\src\commands\Slash\Music\Play.js:84:9) {
  requestBody: {
    files: [],
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: [Array],
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  },
  rawError: {
    message: 'Invalid Form Body',
    code: 50035,
    errors: { embeds: [Object] }
  },
  code: 50035,
  status: 400,
  method: 'PATCH',
  url: 'https://discord.com/api/v10/webhooks/1037257613278203914/aW50ZXJhY3Rpb246MTE3NjE0MTU1MjgxMzM1MTA0MzpETlNIeVlWYldraTRuQm9TckNQYkVqU2M5RnQza0tmNHJxRDd6SnBGd1VHbHpWRk5STThpRUhEbDB0VjlhVFh0ME9OdVBEb1ZpVU9NWFl3T1I0aVhDZzdBRFVHWTZ2WVljcFYyalpYQlNDNm14WXRtMFVEa2tHUG84aHA2UWV2SQ/messages/@original'
}

**Comment by adh319** [comment]
You need to fill everything on the env files, also a working lavalink server

**Comment by KARONAGAMING** [comment]
oke thanks its working now
