### ISSUE TITLE
Can't run the bot the shard problem

### ISSUE THREAD

**Issue by onlinezc** [adh319/Lunox#70]
### Bug description

.

### Step to reproduce

.

### Operating system

web hosting server

### Nodejs version

18.19.0

### Errors / Logs

/home/container/node_modules/discord.js/src/client/Client.js:517
      throw new DiscordjsTypeError(ErrorCodes.ClientInvalidOption, 'shardCount', 'a number greater than or equal to 1');
      ^
TypeError [ClientInvalidOption]: The shardCount option must be a number greater than or equal to 1
    at MainClient._validateOptions (/home/container/node_modules/discord.js/src/client/Client.js:517:13)
    at new Client (/home/container/node_modules/discord.js/src/client/Client.js:80:10)
    at new MainClient (/home/container/src/lunox.js:7:9)
    at Object.<anonymous> (/home/container/src/manager.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18) {
  code: 'ClientInvalidOption'
}

**Comment by adh319** [comment]
If u editing index.js or modify the shardCound then u should at least put 1 for shardCound option

**Comment by onlinezc** [comment]
/home/container/node_modules/discord-hybrid-sharding/dist/Core/ClusterManager.js:106
                throw new TypeError('CLIENT_INVALID_OPTION | Amount of internal shards must be a number.');
                ^
TypeError: CLIENT_INVALID_OPTION | Amount of internal shards must be a number.
    at new ClusterManager (/home/container/node_modules/discord-hybrid-sharding/dist/Core/ClusterManager.js:106:23)
    at Object.<anonymous> (/home/container/src/index.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/container/index.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    
    it's giving me this error now

**Comment by adh319** [comment]
saw you index.js file

**Comment by onlinezc** [comment]
const { ClusterManager } = require("discord-hybrid-sharding"); //imports the sharding manager
require("dotenv").config();

const manager = new ClusterManager(`${__dirname}/manager.js`, {
    totalShards: "1", // you can set to every number you want but for save mode, use "auto" option
    shardsPerClusters: 2, // Default is 2, you can any bigger number you want
    totalClusters: "auto", // you can set to every number you want but for save mode, use "auto" option
    mode: "process", // you can also choose "worker"
    token: process.env.TOKEN || "OTU5NDk1ODgyNTc3OTY5MTky.GyFjhT.0BUCTVpoaWvPHCuJ_FET4Y1MWBWeJybc3NiNic", //paste your token here
});

manager.on("clusterCreate", (cluster) => console.log(`[INFO] Launched Cluster ${cluster.id}`));
manager.spawn({ timeout: -1 });    here's my index.js

**Comment by onlinezc** [comment]
const { ClusterManager } = require("discord-hybrid-sharding"); //imports the sharding manager
require("dotenv").config();

const manager = new ClusterManager(`${__dirname}/manager.js`, {
    totalShards: "1", // you can set to every number you want but for save mode, use "auto" option
    shardsPerClusters: 2, // Default is 2, you can any bigger number you want
    totalClusters: "auto", // you can set to every number you want but for save mode, use "auto" option
    mode: "process", // you can also choose "worker"
    token: process.env.TOKEN || "YOUR_BOT_TOKEN", //paste your token here
});

manager.on("clusterCreate", (cluster) => console.log(`[INFO] Launched Cluster ${cluster.id}`));
manager.spawn({ timeout: -1 }); here's my index.js

**Comment by adh319** [comment]
For more details about Discord Hybrid Sharding, visit [here](https://github.com/meister03/discord-hybrid-sharding). In a simple way, I can explain this:

- `totalCluster`: Specifies how many clusters you want to run on your Discord app.
- `shardsPerClusters`: Represents the total shards that would be deployed per cluster.
- `totalShards`: Encompasses all shards that are deployed.

For example:
Let's say you set `totalClusters` to "auto" and `shardsPerClusters` to 2; then, `totalShards` is "auto". In this case, 2 shards will be deployed for each cluster, and a new cluster will be deployed when the existing clusters have 2 shards already deployed. Here are more examples based on your configuration:

- `totalClusters`: "auto"
- `shardsPerClusters`: 2

Then, `totalShards` can be set to "auto" or 4 at a minimum. "Auto" will deploy a new cluster every 2 shards without a limit; if set to 4, it will deploy 2 clusters based on the `totalShards` limit. Also, if you manually configure the numbers, you should remove the `""`.

**Comment by adh319** [comment]
@onlinezc, has your issue been resolved?
