### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by Lynx-1ST** [adh319/Lunox#81]
### Bug description

Crash on Start

### Step to reproduce

npm i
npm start

### Operating system

Windows 11

### Nodejs version

18

### Errors / Logs

[AntiCrash] | [UnhandledRejection_Logs] | [start] : ===============
Unhandled Rejection at: Promise {
  <rejected> DiscordAPIError[50035]: Invalid Form Body
  embeds[0].description[BASE_TYPE_REQUIRED]: This field is required
      at handleErrors (C:\Users\Administrator\Downloads\Lunox\node_modules\@discordjs\rest\dist\index.js:722:13)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async SequentialHandler.runRequest (C:\Users\Administrator\Downloads\Lunox\node_modules\@discordjs\rest\dist\index.js:1120:23)
      at async SequentialHandler.queueRequest (C:\Users\Administrator\Downloads\Lunox\node_modules\@discordjs\rest\dist\index.js:953:14)
      at async _REST.request (C:\Users\Administrator\Downloads\Lunox\node_modules\@discordjs\rest\dist\index.js:1266:22)
      at async InteractionWebhook.editMessage (C:\Users\Administrator\Downloads\Lunox\node_modules\discord.js\src\structures\Webhook.js:339:15)
      at async ChatInputCommandInteraction.editReply (C:\Users\Administrator\Downloads\Lunox\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:158:17)
      at async Object.run (C:\Users\Administrator\Downloads\Lunox\src\commands\Slash\Music\Play.js:84:9) {
    requestBody: { files: [], json: [Object] },
    rawError: { message: 'Invalid Form Body', code: 50035, errors: [Object] },
    code: 50035,
    status: 400,
    method: 'PATCH',
    url: '*******************'
  }
} reason: DiscordAPIError[50035]: Invalid Form Body
embeds[0].description[BASE_TYPE_REQUIRED]: This field is required
    at handleErrors (C:\Users\Administrator\Downloads\Lunox\node_modules\@discordjs\rest\dist\index.js:722:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (C:\Users\Administrator\Downloads\Lunox\node_modules\@discordjs\rest\dist\index.js:1120:23)
    at async SequentialHandler.queueRequest (C:\Users\Administrator\Downloads\Lunox\node_modules\@discordjs\rest\dist\index.js:953:14)
    at async _REST.request (C:\Users\Administrator\Downloads\Lunox\node_modules\@discordjs\rest\dist\index.js:1266:22)
    at async InteractionWebhook.editMessage (C:\Users\Administrator\Downloads\Lunox\node_modules\discord.js\src\structures\Webhook.js:339:15)
    at async ChatInputCommandInteraction.editReply (C:\Users\Administrator\Downloads\Lunox\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:158:17)
    at async Object.run (C:\Users\Administrator\Downloads\Lunox\src\commands\Slash\Music\Play.js:84:9) {
  requestBody: {
    files: [],
    json: {
      content: undefined,
      tts: false,
      nonce: undefined,
      embeds: [Array],
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    }
  },
  rawError: {
    message: 'Invalid Form Body',
    code: 50035,
    errors: { embeds: [Object] }
  },
  code: 50035,
  status: 400,
  method: 'PATCH',
  url: '***********************************'
}
[AntiCrash] | [UnhandledRejection_Logs] | [end] : ===============

**Comment by unNamexDev** [comment]
Hmm try using Lavalink 3.7.11, I had the same problem and fixed it that way

**Comment by Lynx-1ST** [comment]
> Hmm try using Lavalink 3.7.11, I had the same problem and fixed it that way

thanks, i'll try it
