### ISSUE TITLE
V4 branch control loop button doesnt work

### ISSUE THREAD

**Issue by gamer50082** [adh319/Lunox#89]
### Bug description

the loop button doesnt want to work

### Step to reproduce

enable control and play a music and try to loop the song and the console will log the error

### Operating system

linux

### Nodejs version

20

### Errors / Logs

[AntiCrash] | [UnhandledRejection_Logs] | [start] : ===============
Unhandled Rejection at: Promise {
  <rejected> Error: [Ruvyrias Exception] setLoop arguments are NONE, TRACK and QUEUE.
      at Player.setLoop (/home/container/node_modules/ruvyrias/dist/src/Player/Player.js:270:19)
      at InteractionCollector.<anonymous> (/home/container/src/events/ruvyriasEvents/player/trackStart.js:123:24)
      at InteractionCollector.emit (node:events:530:35)
      at InteractionCollector.handleCollect (/home/container/node_modules/discord.js/src/structures/interfaces/Collector.js:133:14)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} reason: Error: [Ruvyrias Exception] setLoop arguments are NONE, TRACK and QUEUE.
    at Player.setLoop (/home/container/node_modules/ruvyrias/dist/src/Player/Player.js:270:19)
    at InteractionCollector.<anonymous> (/home/container/src/events/ruvyriasEvents/player/trackStart.js:123:24)
    at InteractionCollector.emit (node:events:530:35)
    at InteractionCollector.handleCollect (/home/container/node_modules/discord.js/src/structures/interfaces/Collector.js:133:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[AntiCrash] | [UnhandledRejection_Logs] | [end] : ===============

**Comment by gamer50082** [comment]
[AntiCrash] | [UnhandledRejection_Logs] | [start] : ===============
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'info')
      at module.exports.run (C:\Users\gamer\OneDrive\Documents\GitHub\VRN-Discord-Music-Bot\src\events\ruvyriasEvents\player\trackStart.js:32:42)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} reason: TypeError: Cannot read properties of undefined (reading 'info')
    at module.exports.run (C:\Users\gamer\OneDrive\Documents\GitHub\VRN-Discord-Music-Bot\src\events\ruvyriasEvents\player\trackStart.js:32:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[AntiCrash] | [UnhandledRejection_Logs] | [end] : ===============

**Comment by gamer50082** [comment]
[AntiCrash] | [UnhandledRejection_Logs] | [start] : ===============
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read properties of undefined (reading 'info')
      at module.exports.run (C:\Users\gamer\OneDrive\Documents\GitHub\VRN-Discord-Music-Bot\src\events\ruvyriasEvents\player\trackStart.js:32:42)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
} reason: TypeError: Cannot read properties of undefined (reading 'info')
    at module.exports.run (C:\Users\gamer\OneDrive\Documents\GitHub\VRN-Discord-Music-Bot\src\events\ruvyriasEvents\player\trackStart.js:32:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[AntiCrash] | [UnhandledRejection_Logs] | [end] : ===============

**Comment by gamer50082** [comment]
Now the control doesn’t load at all

**Comment by adh319** [comment]
https://github.com/adh319/Lunox/pull/90 fixed
